# Generated by Django 3.2 on 2022-03-20 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('star', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
