# Generated by Django 3.2 on 2022-03-20 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.IntegerField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(help_text='от 1 до 5. Соответствие: 1- "Ненависть", 2 - "Неприязнь", 3 - "Нейтрально", 4 -"Обожание", 5 - "Любовь".  Возможно нулевое значение.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
