# Generated by Django 3.2 on 2022-03-20 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220320_1752'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0003_auto_20220320_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='item',
            field=models.ManyToManyField(to='catalog.Item'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
