# Generated by Django 3.2 on 2022-03-20 16:24

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Макс 150 символов', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Минимум два слова. Обязательно содержится слово превосходно или роскошно', validators=[catalog.validators.validate_words_brilliants]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
