# Generated by Django 3.2 on 2022-03-20 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220320_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(help_text='Больше 0', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
