# Generated by Django 3.2 on 2022-03-20 17:52

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220320_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Макс 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Минимум два слова. Обязательно содержится слово превосходно или роскошно', validators=[catalog.validators.validate_words_brilliants], verbose_name='Описание'),
        ),
    ]
